---
functional:
  - Пользователи должны иметь возможность менять язык сайта
  - Пользователь должен иметь возможность настраивать свой аккаунт (аватарка, пароль, никнейм, почта)
  - Пользователь должен иметь возможность регистрироваться с помощью GitHub
  - Система должна иметь краткое обучение для новых пользователей
  - Пользователи должны иметь возможность общаться с помощью чата как на главной странице, так и во время игры
  - Пользователь должен иметь возможность выбирать основной язык программирования для соревнований
  - Пользователь должен иметь возможность настраивать сессию
  - Сайт должен содержать доску лидеров
non-functional:
  - Сайт должен быть оптимизирован для работы на разных движках браузеров
  - Сайт должен быть производительным для быстрой загрузки игры
  - Интерфейс должен быть интуитивно понятным
  - Интерфейс должен быть удобным для использования на мобильных устройствах
implicit:
  - Сайт должен быть надежным и доступным в любое время
  - Дизайн должен быть привлекательным
  - Нужна поддежка обновлений и добавление нового контента 