---
functional:
  - Пользователи должны иметь возможность менять язык сайта
  - Пользователь должен иметь возможность настраивать свой аккаунт (аватарка, пароль, никнейм, почта)
  - Пользователь должен иметь возможность регистрироваться с помощью GitHub
  - Система должна иметь краткое обучение для новых пользователей
  - Пользователи должны иметь возможность общаться с помощью чата как на главной странице, так и во время игры
  - Пользователь должен иметь возможность выбирать основной язык программирования для соревнований
  - Пользователь должен иметь возможность настраивать сессию
  - Сайт должен содержать доску лидеров

non-functional:
  - Сайт должен быть оптимизирован для работы на разных движках браузеров
  - Сайт должен быть производительным для быстрой загрузки игры
  - Интерфейс должен быть интуитивно понятным
  - Интерфейс должен быть удобным для использования на мобильных устройствах

implicit:
  - Сайт должен быть надежным и доступным в любое время
  - Дизайн должен быть привлекательным
  - Нужна поддержка обновлений и добавление нового контента

game-mechanics:
  - summary: "Создание игры"
    steps:
      - Пользователь авторизуется
      - Пользователь просто нажимает "Create game" (выбор языка позже)
  - summary: "Подключение к игре"
    steps:
      - Пользователь находится в режиме ожидания второго игрока
      - Игра высвечивается как "доступная для подключения" у других пользователей
      - Второй пользователь нажимает "connect to game"
      - Оба перебрасываются в игру
  - summary: "Игровой процесс"
    steps:
      - Оба игрока видят два редактора: слева - свой редактор, справа - редактор соперника
      - Наверху находится время игры и ниже - задание (позже будет ещё чат слева)
      - Каждый игрок видит код своего соперника в режиме онлайн
      - Каждый игрок имеет кнопку "check" для проверки своего решения. Попыток проверки неограниченно
      - Если один из игроков вылетел из игры, второй может продолжать играть. Первый игрок может переподключиться в любой момент до завершения игры
      - Игра может длиться неограниченное время
  - summary: "Завершение игры"
    steps:
      - Когда один из игроков находит верное решение, обоим игрокам высвечивается модальное окно с информацией о победителе
      - Победитель может выйти из игры по нажатию кнопки "exit", которая становится активной
      - Кнопка "check" у победителя становится неактивной, но он может оставаться в игре и смотреть на свой код
      - Соперник также может выйти из игры или продолжить доигрывать
      - Когда оба игрока вышли, игра считается завершенной и удаляется из памяти
